### ISSUE TITLE
SqlServerExpress with IIdentityServerBuilderExtensions and read users from DB?

### ISSUE THREAD

**Issue by senzacionale** [xyting/RigoFunc.IdentityServer#25]
I want to read users from SqlServerExpress DB, which I have it from IdentiotyServer3 and now I am doing an upgrade to IdentityServer4. I admire your job here.

But I have two questions. Why we need this? 

```
 // what a fuck solution
                .FixCorsIssues(options => {
                    options.AllowAnyOrigin = true;
                }, new string[] {
                    "api/account/lockout",
                    "api/account/register",
                    "api/account/sendcode",
                    "api/account/login",
                    "api/account/verifycode",
                    "api/account/changepassword",
                    "api/account/resetpassword",
                    "api/account/update",
                    "api/weixin/bind",
                    "api/weixin/login"
});
```

Is it possible somehow to use EntityFrameworkCore library like
https://github.com/2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore

Or is MsSQL database with entity framework core fully supported in your project?

And why you have two more projects
- RigoFunc.IdentityServer.DistributedStore
- RigoFunc.IdentityServer.RedisStore

can I simply remove it? I don't need RedisStore and in memory users, I need just users from MsSQL database.

regards
Mitja

**Comment by xyting** [comment]
@senzacionale 

1.  Why we need this? to `Enable CORS`
The latest code had been changed to

```C#
.AllowCors(options => {
         options.AllowAnyOrigin = true;
 });
```

Because we have another package [RigoFunc.Account](https://github.com/xyting/RigoFunc.Account) as **Account Api** abstraction library that uses ASP.NET Core Identity as its claims identity management.
That's mean your WEB/SPA can use this **Account Api**

2. About the users
Because the **Account API** based Microsoft.AspNetCore.Identity, so you can use `Microsoft.AspNetCore.Identity.EntityFrameworkCore` to store your users in DB(Currently, we use MSSQL).

3. Wyou have two more projects?
- RigoFunc.IdentityServer.DistributedStore
- RigoFunc.IdentityServer.RedisStore

This two packages we use to store `TOKEN`, so that your OAuth System(`HOST`) can restart and the issued token always valid before the expire time.

`RigoFunc.IdentityServer.DistributedStore` based on `Microsoft.Extensions.Caching.Abstractions`, so you can use SqlServer or redis (`Microsoft.Extensions.Caching.SqlServer` and `Microsoft.Extensions.Caching.Redis`) to store the TOKEN, and `RigoFunc.IdentityServer.RedisStore` only for Redis.

4. What's still in Memory?
The Clients and the Scopes still in memory. Currently, we haven't any third-party clients, so we doesn't need to store and configure it. and the OAuth System(`HOST`) restart is also OK. If you need to store and configure clients, you can use `RigoFunc.IdentityServer.Services.EntityFrameworkCore` or `TwentyTwenty.IdentityServer4.EntityFrameworkCore`

**Comment by senzacionale** [comment]
Thank you for fast reply. I have external providers as FB, Twitter and Google. Do you have an example how to store them in DB with IdentityServer4 and EFCore?

**Comment by senzacionale** [comment]
Thank you for reply
